version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # mcp-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  #   depends_on:
  #     - rabbitmq
    # Uncomment the following lines to run interactively for development
    # stdin_open: true
    # tty: true 