name: Build & Verify Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".gitignore"

permissions:
  contents: read
  packages: write
  id-token: write # Required for SLSA provenance
  security-events: write # Required for uploading security results
  pull-requests: read

env:
  GO_VERSION: "1.24.3"
  REGISTRY: ghcr.io

jobs:   
  # Simple build verification (for PRs and non-main branches)
  build:
    name: Build Verification
    runs-on: ubuntu-latest
    # Only run for PRs or pushes to non-main branches
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build
        run: go build -v ./...